# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
lang: en
title: Hoang Kien  
email: trungkien02pl@gmail.com 
timezone: Asian/HoChiMinh
description: >- # this means to ignore newlines until "baseurl:"
   I am the king of none.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hoangkien02_
github_username: hoangkien02 
# Build settings
theme: minima
minima:
    date_format: '%Y-%m-%d'
defaults:
  - scope:
      path: ""
    values:
      toc: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-git-history
  - jekyll-twitter-plugin
  - jekyll-youtube
  - jekyll-mermaid
include:
  - _headers
exclude:
  - .git
  - .bundle
  - .idea
  - Gemfile
  - Gemfile.lock
  - _config.yml
  - _layouts
  - vendor
  - Rakefile
  - README.md
